apiVersion: v1
kind: Secret
metadata:
  name: mail-pass
  namespace: monitoring
  labels:
    release: monitoring
type: Opaque
stringData:
  # Kubernetes will encode this to base64 automatically
  gmail-pass: YOUR_ACTUAL_APP_PASSWORD_HERE
